INSERT INTO TUSER VALUES(0,true,'$2a$10$G.btK/hKpoN80ZIvanPh1Obu0mzeWPYEhiHwEgYu4xkW2CWJY2yJW','user');
INSERT INTO TPROFILE VALUES(0,'USER');
INSERT INTO TPERMISSION VALUES(0,'PERM_DELETE_FILE');
INSERT INTO TUSER_PROFILE VALUES(0,0);
INSERT INTO TPROFILE_PERMISSION VALUES(0,0);