INSERT INTO TUSER(id,username,password,enabled,locked,expired,credentials_expired) VALUES(0,'user','$2a$10$A0Hakc4SohjPw0q.UTCdIeLiN6J4bO7fPMBvdmnpRmwyVnGQIcubG',true,false,false,false);
INSERT INTO TPROFILE(id,user_profile_type) VALUES(0,'USER');
INSERT INTO TPERMISSION(id,permission_type) VALUES(0,'PERM_DELETE_FILE');
INSERT INTO TPERMISSION(id,permission_type) VALUES(1,'PERM_UPLOAD_FILE');
INSERT INTO TPERMISSION(id,permission_type) VALUES(2,'PERM_DOWNLOAD_FILE');
INSERT INTO TUSER_PROFILE(user_id,profile_id) VALUES(0,0);
INSERT INTO TPROFILE_PERMISSION(profile_id,permission_id) VALUES(0,0);
INSERT INTO TPROFILE_PERMISSION(profile_id,permission_id) VALUES(0,1);
INSERT INTO TPROFILE_PERMISSION(profile_id,permission_id) VALUES(0,2);